Add files via upload
This was built using pycharm. The keys are in a separate file not uploaded to github. 

When I try and run this program through tweepy, I get the following error:
tweepy.error.TweepError: [{'code': 170, 'message': 'Missing required parameter: status.'}]